-- THE DATA FILE OF THE CAM
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE WORK.CAM_PKG.ALL;

ENTITY DATA_FILE IS
	PORT(
		CLK     : IN  STD_LOGIC;
		RST     : IN  STD_LOGIC;
		WR_EN   : IN  STD_LOGIC;
		WR_ADDR : IN  STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
		WR_DATA : IN  STD_LOGIC_VECTOR(DATA_SIZE - 1 DOWNTO 0);
		RE_ADDR : IN  STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
		RE_DATA : OUT STD_LOGIC_VECTOR(DATA_SIZE - 1 DOWNTO 0)
		);
END DATA_FILE;

ARCHITECTURE STRUCT OF DATA_FILE IS

TYPE REGISTER_FILE IS ARRAY (0 TO DECODER_OUTPUT_VECTOR - 1) OF STD_LOGIC_VECTOR(DATA_SIZE - 1 DOWNTO 0);
SIGNAL RF: REGISTER_FILE := (OTHERS => (OTHERS => '0'));

BEGIN
	-- SEQUENTIAL WRITE
	PROCESS(CLK, RST)
	BEGIN
		IF RST = '1' THEN
			RF       <= (OTHERS => (OTHERS => '0'));
			-- RE_DATA  <= (OTHERS => '0');
		ELSIF RISING_EDGE(CLK) AND WR_EN = '1' THEN
			RF(TO_INTEGER(UNSIGNED(WR_ADDR))) <= WR_DATA;
		END IF;
	END PROCESS;

	-- COMBINATIONAL WRITE
	RE_DATA <= RF(TO_INTEGER(UNSIGNED(RE_ADDR)));

END STRUCT;
