-- A COMPARATOR FOR COMPARING THE KEY_IN AND TAGS
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE WORK.CAM_PKG.ALL;

ENTITY COMPARATOR IS
	PORT(
		KEY_IN    : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);  -- KEY INPUT
        	IN_Q      : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);  -- STORED TAG COMES FROM EACH D-FLIP FLOP
        	COUT      : OUT STD_LOGIC                                    -- 1 IF THE KET AND TAG ARE MATCHED
		);
END COMPARATOR;

ARCHITECTURE BEHAV OF COMPARATOR IS
SIGNAL RES_VEC : STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0) := (OTHERS => '1');
BEGIN
	COUT <= '1' WHEN (KEY_IN XNOR IN_Q) = RES_VEC ELSE '0'; -- 'XNOR' EACH BIT AND 'AND' ALL RESULTS (COUT IS 1 ONLY IF ALL 22 BITS ARE EAQUAL)
END BEHAV;
