-- A D-FLIP FLOP WITH SYNCHORONOUS ENABLE
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE WORK.CAM_PKG.ALL;

ENTITY D_FF IS
	PORT(
		CLK    : IN  STD_LOGIC; 
		RST    : IN  STD_LOGIC; 
		EN     : IN  STD_LOGIC; 
		D      : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);
		Q      : OUT STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0)
		);
END D_FF;

ARCHITECTURE BEHAV OF D_FF IS
BEGIN
	PROCESS(CLK, RST)
	BEGIN
		IF (RST = '1') THEN
			Q <= (OTHERS => '0'); -- RESETS THE OUTPUT
		ELSIF (CLK'EVENT AND CLK = '1') THEN
			IF (EN = '1') THEN
				Q <= D;       -- UPDATES THE OUTPUT
			END IF;
		END IF;
	END PROCESS;
END BEHAV;
