-- DECODER
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE WORK.CAM_PKG.ALL;

ENTITY DECODER IS
	PORT(
		DEC_WR_EN     : IN  STD_LOGIC; 
		IN_HIT        : IN  STD_LOGIC;
		REP_ADDR      : IN  STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
		OUT_VEC       : OUT STD_LOGIC_VECTOR(DECODER_OUTPUT_VECTOR - 1 DOWNTO 0)
		);
END DECODER;

ARCHITECTURE BEHAV OF DECODER IS

BEGIN
	PROCESS(DEC_WR_EN, IN_HIT, REP_ADDR)
	VARIABLE TEMP_VEC : STD_LOGIC_VECTOR(DECODER_OUTPUT_VECTOR - 1 DOWNTO 0);
	BEGIN
		TEMP_VEC := (OTHERS => '0');
		IF DEC_WR_EN = '1' AND IN_HIT = '0' THEN 
			TEMP_VEC(TO_INTEGER(UNSIGNED(REP_ADDR))) := '1';
		END IF;
		OUT_VEC <= TEMP_VEC;
	END PROCESS;
END BEHAV;