-- THE KEY FILE OF THE CAM
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE WORK.CAM_PKG.ALL;

ENTITY KEY_FILE IS
	PORT(
		KFCLK         : IN  STD_LOGIC;
		KFRST         : IN  STD_LOGIC;
		WR_EN         : IN  STD_LOGIC;
		KEY_IN        : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);
		HIT_OUT       : OUT STD_LOGIC;
		ADDRESS_OUT   : OUT STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0)
		);
END KEY_FILE;

ARCHITECTURE STRUCT OF KEY_FILE IS

-- COMPONENTS DECLARATIONS
-- MATCHING CIRCUIT
COMPONENT MATCHING_CIRCUIT 
	PORT(
		MKEY_IN    : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);
		TAGS       : IN  STD_LOGIC_VECTOR(TAGS_SIZE - 1 DOWNTO 0);
		MADDRESS   : OUT STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
		MHIT       : OUT STD_LOGIC
		);
END COMPONENT; 

-- D-FLIP FLOP
COMPONENT D_FF 
	PORT(
		CLK    : IN  STD_LOGIC; 
		RST    : IN  STD_LOGIC; 
		EN     : IN  STD_LOGIC; 
		D      : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);
		Q      : OUT STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0)
		);
END COMPONENT;

-- REPLACEMENT POINTER
COMPONENT REPLACEMENT_POINTER 
	PORT(
		CLK     : IN  STD_LOGIC; 
		RST     : IN  STD_LOGIC; 
		RP_HIT  : IN  STD_LOGIC;
		POINTER : OUT STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0)
		);

END COMPONENT;

--MULTIPLEXER
COMPONENT MULTIPLEXER 
	PORT(
		IN1      : IN  STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
		IN2      : IN  STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0); 
		SEL      : IN  STD_LOGIC;
		ADDR_OUT : OUT STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0)
		);
END COMPONENT;

-- DECODER
COMPONENT DECODER 
	PORT(
		DEC_WR_EN     : IN  STD_LOGIC; 
		IN_HIT        : IN  STD_LOGIC;
		REP_ADDR      : IN  STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
		OUT_VEC       : OUT STD_LOGIC_VECTOR(DECODER_OUTPUT_VECTOR - 1 DOWNTO 0)
		);
END COMPONENT;

-- INTERNAL SIGNALS
SIGNAL HIT_SIG        : STD_LOGIC := '0';
SIGNAL REPDEC_ADDR    : STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
SIGNAL MATMUX_ADDR    : STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
SIGNAL DECDFF_VEC     : STD_LOGIC_VECTOR(DECODER_OUTPUT_VECTOR - 1 DOWNTO 0):= (OTHERS => '0');
SIGNAL DFFMAT_VEC     : STD_LOGIC_VECTOR(TAGS_SIZE - 1 DOWNTO 0);

BEGIN

-- COMPONENTS INSTANTITIONS
-- INSTANTIATE MATCHING UNIT
MATCHING_INST: MATCHING_CIRCUIT
	PORT MAP(
			MKEY_IN    => KEY_IN,
			TAGS       => DFFMAT_VEC,
			MADDRESS   => MATMUX_ADDR,
			MHIT       => HIT_SIG
			);

-- INSTANTIATE D-FLIPFLOPS
GEN_COMPARATORS: FOR I IN 0 TO DECODER_OUTPUT_VECTOR - 1 GENERATE
    	BEGIN
        DFF_INST: D_FF
            	PORT MAP(
			CLK    => KFCLK,
			RST    => KFRST,
			EN     => DECDFF_VEC(I), 
			D      => KEY_IN,
			Q      => DFFMAT_VEC(((I+1) * KEY_IN_SIZE) - 1 DOWNTO I * KEY_IN_SIZE)
			);
    	END GENERATE;

-- INSTANTIATE REPLACMENT POINTER
RP_INST: REPLACEMENT_POINTER
	PORT MAP(
			CLK     => KFCLK, 
			RST     => KFRST, 
			RP_HIT  => HIT_SIG,
			POINTER => REPDEC_ADDR
			);

-- INSTANTIATE MULTIPLEXER
MUX_INST: MULTIPLEXER
	PORT MAP(
			IN1      => REPDEC_ADDR,
			IN2      => MATMUX_ADDR, 
			SEL      => HIT_SIG,
			ADDR_OUT => ADDRESS_OUT
			);

-- INSTANTIATE DECODER
DEC_INST: DECODER
	PORT MAP(
			DEC_WR_EN     => WR_EN, 
			IN_HIT        => HIT_SIG,
			REP_ADDR      => REPDEC_ADDR,
			OUT_VEC       => DECDFF_VEC
			);


HIT_OUT <= HIT_SIG;
END STRUCT;




