-- MATCHING CIRCUIT
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE WORK.CAM_PKG.ALL;

ENTITY MATCHING_CIRCUIT IS
	PORT(
		MKEY_IN    : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);
		TAGS       : IN  STD_LOGIC_VECTOR(TAGS_SIZE - 1 DOWNTO 0);
		MADDRESS   : OUT STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
		MHIT       : OUT STD_LOGIC
		);
END MATCHING_CIRCUIT;

ARCHITECTURE BEHAV OF MATCHING_CIRCUIT IS

COMPONENT COMPARATOR 
	PORT(
		KEY_IN    : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);  
        	IN_Q      : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);  
        	COUT      : OUT STD_LOGIC                       
		);
END COMPONENT;

COMPONENT PRIORITY_ENCODER 
	PORT(
		MATCH_FLAGS : IN  STD_LOGIC_VECTOR(DECODER_OUTPUT_VECTOR - 1 DOWNTO 0);   
		ADDRESS     : OUT STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);    
		HIT         : OUT STD_LOGIC                        
		);
END COMPONENT;

SIGNAL TAGFLAGS : STD_LOGIC_VECTOR(DECODER_OUTPUT_VECTOR - 1 DOWNTO 0); -- SIGNAL FOR PRIORITY ENCODER

BEGIN
	
    	GEN_COMPARATORS: FOR I IN 0 TO DECODER_OUTPUT_VECTOR - 1 GENERATE
    	BEGIN
        COMP_INST: COMPARATOR
            	PORT MAP (
                	KEY_IN => MKEY_IN,
                	IN_Q   => TAGS(((I+1) * KEY_IN_SIZE) - 1 DOWNTO I * KEY_IN_SIZE),  
                	COUT   => TAGFLAGS(I)
            	);
    	END GENERATE;

    
	PRIORITY_ENC: PRIORITY_ENCODER
        PORT MAP (
            MATCH_FLAGS => TAGFLAGS,
            ADDRESS     => MADDRESS,
            HIT         => MHIT
        );

END BEHAV;

