-- SIMPLE 2 TO 1 MULTIPLEXER WITH 6 BIT INPUTS AND OUTPUT
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE WORK.CAM_PKG.ALL;

ENTITY MULTIPLEXER IS
	PORT(
		IN1      : IN  STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
		IN2      : IN  STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0); 
		SEL      : IN  STD_LOGIC;
		ADDR_OUT : OUT STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0)
		);
END MULTIPLEXER;

ARCHITECTURE BEHAV OF MULTIPLEXER IS
BEGIN
	ADDR_OUT <= IN2 WHEN SEL = '1' ELSE IN1;
END BEHAV;
