-- PRIORITY ENCODER FOR THE MATCH CIRCUIT
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE WORK.CAM_PKG.ALL;

ENTITY PRIORITY_ENCODER IS
	PORT(
		MATCH_FLAGS : IN  STD_LOGIC_VECTOR(DECODER_OUTPUT_VECTOR - 1 DOWNTO 0);  -- 64-BIT MATCH FLAGS
		ADDRESS     : OUT STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);        -- 6-BIT INDEX
		HIT         : OUT STD_LOGIC                                              -- THIS TURNS 1 IF ANY HIT HAPPENS
		);
END PRIORITY_ENCODER;

ARCHITECTURE BEHAV OF PRIORITY_ENCODER IS
BEGIN
    PROCESS(MATCH_FLAGS)
    BEGIN
        ADDRESS <= (OTHERS => '0');
        HIT   <= '0';
        -- PRIORITY: LOWEST INDEX HAS HIGHER PRIORITY
        FOR I IN 0 TO DECODER_OUTPUT_VECTOR - 1 LOOP
            IF MATCH_FLAGS(I) = '1' THEN
                ADDRESS <= STD_LOGIC_VECTOR(TO_UNSIGNED(I, KEY_FILE_OUTPUT));
                HIT   <= '1';
                EXIT;  -- EXITS ON FIRST MATCH
            END IF;
        END LOOP;
    END PROCESS;
END BEHAV;
