-- REPLACEMENT POINTER
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE WORK.CAM_PKG.ALL;

ENTITY REPLACEMENT_POINTER IS
	PORT(
		CLK     : IN  STD_LOGIC; 
		RST     : IN  STD_LOGIC; 
		RP_HIT  : IN  STD_LOGIC;
		POINTER : OUT STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0)
		);

END ENTITY;

ARCHITECTURE BEHAV OF REPLACEMENT_POINTER IS

SIGNAL PTR_TEMP : UNSIGNED(KEY_FILE_OUTPUT - 1 DOWNTO 0) := (OTHERS => '0');

BEGIN
	PROCESS(CLK, RST)
	BEGIN
		IF RST = '1' THEN
			PTR_TEMP <= (OTHERS => '0');
		ELSIF RISING_EDGE(CLK) THEN
			IF RP_HIT = '0' THEN  -- WHEN MISS HAPPENS
				IF PTR_TEMP = DECODER_OUTPUT_VECTOR - 1 THEN 
					PTR_TEMP <= (OTHERS => '0'); -- RETURN TO THE FIRST INDEX
				ELSE
					PTR_TEMP <= PTR_TEMP + 1;
				END IF;
			END IF;
		END IF;
	END PROCESS;
POINTER <= STD_LOGIC_VECTOR(PTR_TEMP);
END BEHAV;
