-- A UNIVERSAL PACKAGE TO CONFIGURE CAM COMMON TYPES AND CONSTANTS
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;

PACKAGE CAM_PKG IS

-- KEY FILE
CONSTANT KEY_IN_SIZE     : INTEGER := 22;
CONSTANT KEY_FILE_OUTPUT : INTEGER := 6;

-- MATCHING CIRCUIT
CONSTANT TAGS_SIZE : INTEGER := 1408;

-- DECODER
CONSTANT DECODER_OUTPUT_VECTOR : INTEGER := 64;

-- DATA FILE
CONSTANT DATA_SIZE : INTEGER := 32;

END PACKAGE;