-- CONTENT ADDRESSABLE MEMORY'S MAIN FILE
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.NUMERIC_STD.ALL;
USE WORK.CAM_PKG.ALL;

ENTITY CAM IS
	PORT(
		UNI_CLK     : IN  STD_LOGIC;
		UNI_RST     : IN  STD_LOGIC;
		UNI_KEY_IN  : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);
		UNI_WR_EN   : IN  STD_LOGIC;
		INPUT_DATA  : IN  STD_LOGIC_VECTOR(DATA_SIZE - 1 DOWNTO 0);
		HIT         : OUT STD_LOGIC;
		OUTPUT_DATA : OUT STD_LOGIC_VECTOR(DATA_SIZE - 1 DOWNTO 0)
		);
END CAM;

ARCHITECTURE STRUCT OF CAM IS

-- COMPONENTS DECLARATIONS
-- KEY FILE COMPONENT
COMPONENT KEY_FILE
	PORT(
		KFCLK         : IN  STD_LOGIC;
		KFRST         : IN  STD_LOGIC;
		WR_EN         : IN  STD_LOGIC;
		KEY_IN        : IN  STD_LOGIC_VECTOR(KEY_IN_SIZE - 1 DOWNTO 0);
		HIT_OUT       : OUT STD_LOGIC;
		ADDRESS_OUT   : OUT STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0)
		);
END COMPONENT;

-- DATA FILE COMPONENT
COMPONENT DATA_FILE 
	PORT(
		CLK     : IN  STD_LOGIC;
		RST     : IN  STD_LOGIC;
		WR_EN   : IN  STD_LOGIC;
		WR_ADDR : IN  STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
		WR_DATA : IN  STD_LOGIC_VECTOR(DATA_SIZE - 1 DOWNTO 0);
		RE_ADDR : IN  STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);
		RE_DATA : OUT STD_LOGIC_VECTOR(DATA_SIZE - 1 DOWNTO 0)
		);
END COMPONENT;

-- INTERNAL CONNECTIONS
SIGNAL KEYDATA_ADDR : STD_LOGIC_VECTOR(KEY_FILE_OUTPUT - 1 DOWNTO 0);

BEGIN

-- COMPONENTS INSTANTIATIONS
-- INSTANTIATE KEY FILE
KEY_INST: KEY_FILE
	PORT MAP(
			KFCLK         => UNI_CLK,
			KFRST         => UNI_RST,
			WR_EN         => UNI_WR_EN,
			KEY_IN        => UNI_KEY_IN,
			HIT_OUT       => HIT,
			ADDRESS_OUT   => KEYDATA_ADDR
			);

-- INSTANTIATE DATA FILE
DATA_INST: DATA_FILE
	PORT MAP(
			CLK       => UNI_CLK,
			RST       => UNI_RST,
			WR_EN     => UNI_WR_EN,
			WR_ADDR   => KEYDATA_ADDR,
			WR_DATA   => INPUT_DATA,
			RE_ADDR   => KEYDATA_ADDR,
			RE_DATA   => OUTPUT_DATA
			);

END STRUCT;
